'use server';
/**
 * @fileOverview A flow to summarize alerts for a security operator, providing a daily summary of alerts,
 * highlighting trends and potential issues.
 *
 * - summarizeAlertsForOperator - A function that generates the alert summary.
 * - SummarizeAlertsForOperatorInput - The input type for the summarizeAlertsForOperator function.
 * - SummarizeAlertsForOperatorOutput - The return type for the summarizeAlertsForOperator function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import { type Alert } from '@/lib/types';

const SummarizeAlertsForOperatorInputSchema = z.object({
  alerts: z.array(
    z.object({
      id: z.number(),
      person_id: z.number(),
      behaviour_type: z.string(),
      confidence: z.number(),
      timestamp: z.string(),
      camera_id: z.string(),
      snapshot_path: z.string().optional(),
    })
  ).describe('An array of alerts generated by the system.'),
});
export type SummarizeAlertsForOperatorInput = z.infer<typeof SummarizeAlertsForOperatorInputSchema>;

const SummarizeAlertsForOperatorOutputSchema = z.object({
  summary: z.string().describe('A concise, natural language summary of the alerts for a security operator. Highlight key trends, frequent locations, and potential security issues. Be brief and to the point.'),
});
export type SummarizeAlertsForOperatorOutput = z.infer<typeof SummarizeAlertsForOperatorOutputSchema>;

export async function summarizeAlertsForOperator(input: { alerts: Alert[] }): Promise<SummarizeAlertsForOperatorOutput> {
  // The Genkit flow expects a specific input structure that might differ from the internal Alert type.
  // We map the alerts to the expected schema.
  const flowInput: SummarizeAlertsForOperatorInput = {
    alerts: input.alerts.map(a => ({
      ...a,
      behaviour_type: a.behaviour_type,
    }))
  };
  return summarizeAlertsForOperatorFlow(flowInput);
}

const summarizeAlertsPrompt = ai.definePrompt({
  name: 'summarizeAlertsPrompt',
  input: {schema: SummarizeAlertsForOperatorInputSchema},
  output: {schema: SummarizeAlertsForOperatorOutputSchema},
  prompt: `You are a security analyst tasked with summarizing the daily alerts generated by a surveillance system.

  Analyze the following alerts and provide a concise, natural language summary for a security operator.
  Highlight any key trends (e.g., repeated behaviors, specific locations), potential security issues, or notable patterns.
  The summary should be informative and actionable, enabling a security operator to quickly assess the day's situation.
  Keep the summary to 2-3 sentences.

  Alerts:
  {{#if alerts.length}}
  {{#each alerts}}
  - ID: {{id}}, Person ID: {{person_id}}, Behavior: {{behaviour_type}}, Confidence: {{confidence}}, Timestamp: {{timestamp}}, Camera: {{camera_id}}
  {{/each}}
  {{else}}
  No alerts were recorded for this period.
  {{/if}}

  Summary:`,
});

const summarizeAlertsForOperatorFlow = ai.defineFlow(
  {
    name: 'summarizeAlertsForOperatorFlow',
    inputSchema: SummarizeAlertsForOperatorInputSchema,
    outputSchema: SummarizeAlertsForOperatorOutputSchema,
  },
  async input => {
    const {output} = await summarizeAlertsPrompt(input);
    return output!;
  }
);
