'use server';
/**
 * @fileOverview A flow to summarize alerts for a security operator, providing a daily summary of alerts,
 * highlighting trends and potential issues.
 *
 * - summarizeAlertsForOperator - A function that generates the alert summary.
 * - SummarizeAlertsForOperatorInput - The input type for the summarizeAlertsForOperator function.
 * - SummarizeAlertsForOperatorOutput - The return type for the summarizeAlertsForOperator function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SummarizeAlertsForOperatorInputSchema = z.object({
  alerts: z.array(
    z.object({
      id: z.number(),
      person_id: z.number(),
      behaviour_type: z.string(),
      confidence: z.number(),
      timestamp: z.string(),
      camera_id: z.string(),
      snapshot_path: z.string().optional(),
    })
  ).describe('An array of alerts generated by the system.'),
});
export type SummarizeAlertsForOperatorInput = z.infer<typeof SummarizeAlertsForOperatorInputSchema>;

const SummarizeAlertsForOperatorOutputSchema = z.object({
  summary: z.string().describe('A summary of the alerts, highlighting key trends and potential issues.'),
});
export type SummarizeAlertsForOperatorOutput = z.infer<typeof SummarizeAlertsForOperatorOutputSchema>;

export async function summarizeAlertsForOperator(input: SummarizeAlertsForOperatorInput): Promise<SummarizeAlertsForOperatorOutput> {
  return summarizeAlertsForOperatorFlow(input);
}

const summarizeAlertsPrompt = ai.definePrompt({
  name: 'summarizeAlertsPrompt',
  input: {schema: SummarizeAlertsForOperatorInputSchema},
  output: {schema: SummarizeAlertsForOperatorOutputSchema},
  prompt: `You are a security analyst tasked with summarizing the daily alerts generated by a surveillance system.

  Analyze the following alerts and provide a concise summary, highlighting any key trends, potential issues, or notable patterns.
  The summary should be informative and actionable, enabling a security operator to quickly assess the situation and take appropriate action.

  Alerts:
  {{#each alerts}}
  - ID: {{id}}, Person ID: {{person_id}}, Behavior: {{behaviour_type}}, Confidence: {{confidence}}, Timestamp: {{timestamp}}, Camera: {{camera_id}}
  {{/each}}

  Summary:`,
});

const summarizeAlertsForOperatorFlow = ai.defineFlow(
  {
    name: 'summarizeAlertsForOperatorFlow',
    inputSchema: SummarizeAlertsForOperatorInputSchema,
    outputSchema: SummarizeAlertsForOperatorOutputSchema,
  },
  async input => {
    const {output} = await summarizeAlertsPrompt(input);
    return output!;
  }
);
